version: "3.9"
services:
  twenty-front:
    image: pdkhai/twenty-front
    restart: always
    ports:
      - "3001:3000"
    depends_on:
      - postgres
  twenty-server:
    image: pdkhai/twenty-server
    restart: always
    ports:
      - "3002:3000"
    depends_on:
      - postgres
  postgres:
    image: postgres:15.2-alpine
    restart: always
    command: postgres -c 'max_connections=1000'
    volumes:
    - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data
volumes:
  pgdata:
